name: Build

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Build
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: Setup builder
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.reactions.createForIssueComment({
              comment_id: context.payload.comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: 'rocket'
            })
      - uses: actions/checkout@v1
      - name: Build and tag Docker image
        run: |
          docker build --file Dockerfile \
            --tag amatas:${GITHUB_SHA::8} \
            --tag amatas:latest .
      - name: Add commit comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var msg = "```\n \"image\" = \"amatas\"\n \"tag\" = \"" + context.sha.substr(0,7) + "\"\n```"

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
