name: Build

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Build
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: Setup builder
        run: |
          env
          apt install -y jq curl
          echo "Build ${GITHUB_SHA::8}"
      - name: Add commit comment
        run: |
          jq -nc '{"body": "App built\n```\nID: $GITHUB_SHA\n```\n"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$GITHUB_SHA/comments"
