name: Build

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Build
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: Setup builder
        run: |
          echo "Build ${GITHUB_SHA::8}"
      - name: Add commit comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var msg = "ID: GITHUB_SHA"

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
